site_name: CassIO
repo_url: https://github.com/CassioML/cassio

nav:
  - Home: index.md
  - Examples:
    - Overview: frameworks/examples/index.md
    - Quickstart: frameworks/examples/quickstart.ipynb
  - Reference:
      - Home: reference/index.md
      - Init: reference/init.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#    - pymdownx.arithmatex
# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - stylesheets/theme.css

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocs-jupyter:
      include_source: True
      include: ["*.ipynb"]
      ignore: ["**/.colab/*.ipynb", "**/.ipynb_checkpoints/*.ipynb"]

# Theme
theme:
  name: material
  custom_dir: overrides
  language: en
  favicon: img/favicon.svg
  logo: images/cassio_logo1_transparent_small.png
  features:
    - navigation.tabs.sticky
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch color
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch color
extra:
  analytics:
    provider: google
    property: G-5D1VE6YCN1
