site_name: CassIO
nav:
  - Home:
      - Welcome: index.md
      - General architecture: general_architecture.md
      - DB Setup: db_setup.md
      - API Setup: api_setup.md
      - Local DB Setup: local_db_setup.md
  - LangChain:
    - About: frameworks/langchain/about.md
    - Setup: frameworks/langchain/setup.md
    - Prompt Templates:
      - Intro: frameworks/langchain/prompt-templates-basic.ipynb
      - Chat templates: frameworks/langchain/chat-prompt-templates.ipynb
      - Partialing: frameworks/langchain/prompt-templates-partialing.ipynb
    - Advanced Prompt Templates:
        - Custom templates: frameworks/langchain/prompt-templates-engine.ipynb
        - Feast/Cassandra, setup: frameworks/langchain/prompt-templates-feast-setup.md
        - Feast Prompt Templates: frameworks/langchain/prompt-templates-feast.ipynb
    - Memory:
        - Base class: frameworks/langchain/memory-basic.ipynb
        - Conversation Buffer Memory: frameworks/langchain/memory-conversationbuffermemory.ipynb
        - Summary Buffer Memory: frameworks/langchain/memory-summarybuffermemory.ipynb
    - Caching:
        - Caching LLM responses: frameworks/langchain/caching-llm-responses.ipynb
    - Vector Search:
        - About: frameworks/langchain/vector-similarity-search.md
        - Semantic LLM response caching: frameworks/langchain/semantic-caching-llm-responses.ipynb
        - VectorStore/Q&A, quickstart: frameworks/langchain/qa-basic.ipynb
        - VectorStore/Q&A, learn more: frameworks/langchain/qa-advanced.ipynb
        - VectorStore, MMR support: frameworks/langchain/qa-maximal-marginal-relevance.ipynb
        - VectorStore-backed memory: frameworks/langchain/memory-vectorstore.ipynb

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#    - pymdownx.arithmatex
# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - stylesheets/theme.css

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocs-jupyter:
      include_source: True
      include: ["*.ipynb"]
      ignore: ["**/.colab/*.ipynb", "**/.ipynb_checkpoints/*.ipynb"]

# Theme
theme:
  name: material
  custom_dir: overrides
  language: en
  favicon: img/favicon.svg
  logo: images/cassio_logo1_transparent_small.png
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch color
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch color
