site_name: CassIO
nav:
  - Home: index.md
  - Langchain:
    - Setup: examples/langchain/setup.md
    - Prompt templates: examples/langchain/prompt_templates.md
theme: readthedocs
# markdown_extensions:
#    - pymdownx.arithmatex
# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
